container:
        image: liuchong/rustup:latest
        cpu: 1
        memory: 1G



test_task:
        test_cargo_build_script:
                - rustup default nightly
                - cargo build
        test_cargo_release_script:
                - rustup default nightly
                - cargo build --release
        test_cargo_run_script:
                - rustup default nightly
                - cargo run 

